### ISSUE TITLE
New DLC secret religion scripted trigger needed

### ISSUE THREAD

**Issue by Ispil** [zijistark/EMF#524]
Next time sr_codegen.py is ran, needs to be modified to include a "emf_sr_does_cult_need_JD" scripted trigger for the 3 new religions added by the JD DLC.

**Comment by zijistark** [comment]
Looks like vanilla's event that uses this puts `taoist` (`indian_group`) + `bon` (`pagan_group`) + `khurmazta` (`zoroastrian_group`) behind a *TOG* DLC-lock. I'm guessing this is an error for `taoist` (I would expect JD to be required to play them), but the other two do indeed traditionally follow the TOG playable pattern (pagans and zoroastrians).

Consequently, I'm not entirely sure what `emf_sr_does_cult_need_JD` should actually be.

**Comment by zijistark** [comment]
Further investigation reveals that the DLC-wall on these 3 new religions is a bit more complicated than we're accustomed. Seems at least `bon` and `khurmazta` are unlocked by JD **or** TOG. With `taoist`, I _assume_ it's still JD-only, making it the one irregular religion in terms of religion group mapping to DLC-unlocked playability.

Eh, I'm not going to try too hard on this. It's used in one fairly minor place, and it's not entirely clear to me how necessary it is anyway (plus, vanilla's "reference" implementation already has its brains blown all over the wall).

**Comment by zijistark** [comment]
Er, got confirmation that `taoist` is also unlocked by JD **or** RoI. This should be easy then, since the religion group variants still hold. The logic that uses these scripted triggers needs to be massaged a bit to allow multiple DLCs to unlock the same religion, and for JD's reqs, they're not RG-based but simply R-based and a supplement to the already existing DLC locks.

**Comment by zijistark** [comment]
Implemented and code regenerated.
