### ISSUE TITLE
Isis visible even when "supernatural events" turned off

### ISSUE THREAD

**Issue by pseudomonas** [zijistark/EMF#679]
Whenever I sort people by stats, Isis is always at the top of the list. This is kind of jarring given I deselected "supernatural events" and "absurd events"; can her visibility be suppressed when these are toggled off?

**Comment by pseudomonas** [comment]
I feel that it would be fitting for immortal (and other flavours of superhuman) characters to be conditional on the "supernatural" toggle in general.

**Comment by zijistark** [comment]
> can her visibility be suppressed when these are toggled off?

No. Her existence is necessary for the mod to be able to do what it does, so deactivating her entirely is not an option, and there's no way to hide her from the Find Character function. Since she will never interact with you even if you try, I wouldn't worry about any sort of supernatural events or absurd events as a consequence.
